SELECT * FROM STAGING.ACCOUNT WHERE ACCOUNT_ID='A0005';
--UPDATE STAGING.ACCOUNT SET ACCOUNT_STATUS='ACTIVE',created_load_id=205 WHERE ACCOUNT_ID='A0005'; 
SELECT * FROM TRANSFORM.SL_ACCOUNT WHERE ACCOUNT_ID='A0005';