name: UPI_Fraud_Monitoring
version: 1.0.0
config-version: 2
profile: default

model-paths:
  - models
macro-paths:
  - macros
seed-paths:
  - seeds

models:
  UPI_Fraud_Monitoring:
    bronze:
      raw_views:
        +materialized: view
        +schema: TRANSFORM
      views:
        +materialized: view
        +schema: TRANSFORM
    silver:
      +materialized: incremental
      +schema: TRANSFORM
      +on_schema_change: append_new_columns
    gold:
      +materialized: incremental
      +schema: ANALYTICS
      +on_schema_change: append_new_columns

seeds:
  UPI_Fraud_Monitoring:
    dim_fraud_rule:
      +schema: TRANSFORM
      +quote_columns: true
