CREATE TABLE GLD_INVESTIGATION_QUEUE
(
    CASE_ID                 VARCHAR(100),
    ALERT_ID                VARCHAR(100),
    CUSTOMER_ID             VARCHAR(50),
    TRANSACTION_ID          VARCHAR(100),
    PRIORITY                VARCHAR(20),
    ASSIGNED_TO             VARCHAR(100),
    CASE_STATUS             VARCHAR(30),
    CUSTOMER_RISK_SCORE     NUMBER,
    ALERT_SEVERITY          VARCHAR(20),
    CREATED_TS              TIMESTAMP,
    ASSIGNED_TS             TIMESTAMP,
    CLOSED_TS               TIMESTAMP,
    SLA_HOURS               NUMBER
);

Step 1: Select Open Alerts
-------------------------------------
CREATE OR REPLACE TEMP TABLE TMP_OPEN_ALERTS AS

SELECT
    ALERT_ID,
    CUSTOMER_ID,
    TRANSACTION_ID,
    RISK_SCORE,
    SEVERITY,
    CREATED_TS
FROM GLD_FRAUD_ALERT
WHERE ALERT_STATUS='OPEN';

Step 2: Enrich with Customer Risk
----------------------------------------------
CREATE OR REPLACE TEMP TABLE TMP_CASES AS
SELECT
    A.ALERT_ID,
    A.CUSTOMER_ID,
    A.TRANSACTION_ID,
    A.RISK_SCORE,
    A.SEVERITY,
    C.CUSTOMER_RISK_SCORE,
    A.CREATED_TS
FROM TMP_OPEN_ALERTS A
LEFT JOIN GLD_CUSTOMER_RISK C
ON A.CUSTOMER_ID=C.CUSTOMER_ID;

Step 3: Determine Priority
----------------------------------
ALERT_SEVERITY = CRITICAL OR CUSTOMER_RISK_SCORE > 120

CASE
WHEN SEVERITY='CRITICAL' THEN 'P1'
WHEN CUSTOMER_RISK_SCORE >= 120 THEN 'P1'
WHEN SEVERITY='HIGH' THEN 'P2'
WHEN SEVERITY='MEDIUM' THEN 'P3'
ELSE 'P4'
END AS PRIORITY

Step 4: Assign SLA
---------------------------
CASE 


ELSE 24
END AS SLA_HOURS

Step 5: Assign Investigation Team
-------------------------------------------------
CASE
WHEN PRIORITY='P1' THEN 'L3_FRAUD_TEAM'
WHEN PRIORITY='P2' THEN 'L2_FRAUD_TEAM'
ELSE 'L1_FRAUD_TEAM'
END AS ASSIGNED_TO

Step 6: Load GLD_INVESTIGATION_QUEUE
--------------------------------------------------------------
INSERT INTO GLD_INVESTIGATION_QUEUE
(
    CASE_ID,
    ALERT_ID,
    CUSTOMER_ID,
    TRANSACTION_ID,
    PRIORITY,
    ASSIGNED_TO,
    CASE_STATUS,
    CUSTOMER_RISK_SCORE,
    ALERT_SEVERITY,
    CREATED_TS,
    ASSIGNED_TS,
    SLA_HOURS
)

SELECT
    'CASE_' || UUID_STRING(),
    ALERT_ID,
    CUSTOMER_ID,
    TRANSACTION_ID,
    CASE
        WHEN SEVERITY='CRITICAL' THEN 'P1'
        WHEN CUSTOMER_RISK_SCORE >=120 THEN 'P1'
        WHEN SEVERITY='HIGH' THEN 'P2'
        WHEN SEVERITY='MEDIUM' THEN 'P3'
        ELSE 'P4'
    END,
    CASE
        WHEN SEVERITY='CRITICAL' THEN 'L3_FRAUD_TEAM'
        WHEN SEVERITY='HIGH' THEN 'L2_FRAUD_TEAM'
        ELSE 'L1_FRAUD_TEAM'
    END,
    'OPEN',
    CUSTOMER_RISK_SCORE,
    SEVERITY,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP(),
    CASE
        WHEN SEVERITY='CRITICAL' THEN 2
        WHEN SEVERITY='HIGH' THEN 4
        WHEN SEVERITY='MEDIUM'  THEN 8
        ELSE 24
    END
FROM TMP_CASES;
