version: 2

sources:
  - name: staging
    schema: STAGING   # <-- replace with the actual schema in Snowflake
    tables:
      - name: account
      - name: beneficiary
      - name: collect_request
      - name: customer
      - name: device_registry
      - name: login_activity
      - name: merchant
      - name: password_change
      - name: upi_transaction
      - name: watchlist
      - name: UPI_TRANSACTION_FACT